/*
 * Copyright (c) 2008-2014 Maxifier Ltd. All Rights Reserved.
 */
package stub;

/** THIS IS AUTOGENERATED STUFF FOR FINAL FIELD INITIALIZATION */
/**
 * THIS CLASS WAS GENERATED AUTOMATICALLY WITH StubGen BASED ON IDEA BINARIES
 * DON'T MODIFY IT MANUALLY!

 * @author Alexander Kochurov (alexander.kochurov@maxifier.com)
 */
public class InitializationStub {
     @SuppressWarnings("unchecked")
     public static <T> T get(Class<?> c) {
          if (c == byte.class) {
               return (T)Byte.valueOf((byte)0);
          } else if (c == char.class) {
               return (T)Character.valueOf((char)0);
          } else if (c == short.class) {
               return (T)Short.valueOf((short)0);
          } else if (c == int.class) {
               return (T)Integer.valueOf(0);
          } else if (c == long.class) {
               return (T)Long.valueOf(0L);
          } else if (c == float.class) {
               return (T)Float.valueOf(0F);
          } else if (c == double.class) {
               return (T)Double.valueOf(0D);
          } else if (c == boolean.class) {
               return (T)Boolean.FALSE;
          } else {
               return null;
          }
     }
}
