/*
 * Copyright (c) 2008-2014 Maxifier Ltd. All Rights Reserved.
 */
package stub;

/** THIS IS AUTOGENERATED STUFF FOR FINAL FIELD INITIALIZATION */
/**
 * THIS CLASS WAS GENERATED AUTOMATICALLY WITH StubGen BASED ON IDEA BINARIES
 * DON'T MODIFY IT MANUALLY!

 * @author Alexander Kochurov (alexander.kochurov@maxifier.com)
 */
public class InitializationStub {
     public static <T> T get() { throw new UnsupportedOperationException(); }
}
